name: Terrascan Scan
on:
  push:
    branches: [ "main" ]
jobs:
  terrascan:
    runs-on: ubuntu-latest
    steps:
      - name: checkout to current repository
        uses: actions/checkout@v2
      - name: Run Terrascan Scan
        uses: tenable/terrascan-action@v1.4.1
        with:
          iac_type: terraform
          iac_dir: ${{ github.workspace }}
    continue-on-error: true
  Kubernetes:
    runs-on: ubuntu-latest
    steps:
      - name: checkout to current repository
        uses: actions/checkout@v2
      - name: Run Terrascan Scan
        uses: tenable/terrascan-action@v1.4.1
        with:
          iac_type: k8s
          iac_dir: ${{ github.workspace }}
    continue-on-error: true
  Helm:
    runs-on: ubuntu-latest
    steps:
      - name: checkout to current repository
        uses: actions/checkout@v2
      - name: Run Terrascan Scan
        uses: tenable/terrascan-action@v1.4.1
        with:
          iac_type: helm
          iac_dir: ${{ github.workspace }}
    continue-on-error: true
